"""Initial schema

Revision ID: 84a60d8d4dd6
Revises: 
Create Date: 2026-04-04 18:33:43.997448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a60d8d4dd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'assetId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('assets', 'assetName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'manual',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'mttr',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('assets_assetId_key'), 'assets', type_='unique')
    op.create_index(op.f('ix_assets_assetId'), 'assets', ['assetId'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.add_column('audits', sa.Column('assignedTo', sa.String(), nullable=True))
    op.alter_column('audits', 'assetId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('audits', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audits', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_audits_assetId'), 'audits', ['assetId'], unique=False)
    op.create_index(op.f('ix_audits_assignedTo'), 'audits', ['assignedTo'], unique=False)
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.alter_column('inventory', 'partName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('inventory', 'partNumber',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('inventory', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('inventory_partNumber_key'), 'inventory', type_='unique')
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_partNumber'), 'inventory', ['partNumber'], unique=True)
    op.alter_column('part_reservations', 'partId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('part_reservations', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'RESERVED'::text"))
    op.create_index(op.f('ix_part_reservations_id'), 'part_reservations', ['id'], unique=False)
    op.alter_column('roster', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('roster', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'AVAILABLE'::text"))
    op.alter_column('roster', 'shift',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('roster', 'skills',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_roster_id'), 'roster', ['id'], unique=False)
    op.create_index(op.f('ix_roster_userId'), 'roster', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_userId'), table_name='roster')
    op.drop_index(op.f('ix_roster_id'), table_name='roster')
    op.alter_column('roster', 'skills',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roster', 'shift',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roster', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'AVAILABLE'::text"))
    op.alter_column('roster', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_part_reservations_id'), table_name='part_reservations')
    op.alter_column('part_reservations', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'RESERVED'::text"))
    op.alter_column('part_reservations', 'partId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_inventory_partNumber'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.create_unique_constraint(op.f('inventory_partNumber_key'), 'inventory', ['partNumber'], postgresql_nulls_not_distinct=False)
    op.alter_column('inventory', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('inventory', 'partNumber',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('inventory', 'partName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_assignedTo'), table_name='audits')
    op.drop_index(op.f('ix_audits_assetId'), table_name='audits')
    op.alter_column('audits', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audits', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audits', 'assetId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('audits', 'assignedTo')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_assetId'), table_name='assets')
    op.create_unique_constraint(op.f('assets_assetId_key'), 'assets', ['assetId'], postgresql_nulls_not_distinct=False)
    op.alter_column('assets', 'mttr',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'manual',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'assetName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'assetId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
