"""Add assetType to Asset model

Revision ID: ba9a1e3fe4c4
Revises: 84a60d8d4dd6
Create Date: 2026-04-04 18:50:37.487978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9a1e3fe4c4'
down_revision: Union[str, Sequence[str], None] = '84a60d8d4dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('assetType', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'assetType')
    # ### end Alembic commands ###
